USER_AGENTS = ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:11.0) Gecko/20100101 Firefox/11.0',
               'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:22.0) Gecko/20100 101 Firefox/22.0',
               'Mozilla/5.0 (Windows NT 6.1; rv:11.0) Gecko/20100101 Firefox/11.0',
               ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4) AppleWebKit/536.5 (KHTML, like Gecko  ) '
                'Chrome/19.0.1084.46 Safari/536.5'),
               ('Mozilla/5.0 (Windows; Windows NT 6.1) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/  19.0.1084.46'
                'Safari/536.5'), )

ADSENSE_MIDDLE = '''<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- insert middle -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-2477248594987452"
     data-ad-slot="3727980969"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>'''

BANK_CODE = {'우리은행': '0010001',
             '한국스탠다드차타드은행': '0010002',
             '한국씨티은행': '0010006',
             '대구은행': '0010016',
             '부산은행': '0010017',
             '광주은행': '0010019',
             '제주은행': '0010020',
             '전북은행': '0010022',
             '경남은행': '0010024',
             '중소기업은행': '0010026',
             '한국산업은행': '0010030',
             '국민은행': '0010927',
             '신한은행': '0011625',
             '농협은행': '0013175',
             'KEBKEB하나은행': '0013909',
             '케이뱅크은행': '0014674',
             '수협은행': '0014807',
             '한국카카오은행': '0015130', }

LOAN_CODE = {'현대카드': '0010225',
             '롯데카드': '0010226',
             '비씨카드': '0010227',
             '삼성카드': '0010228',
             '신한카드': '0010229',
             '오케이캐피탈 ': '0010240',
             'KB캐피탈': '0010250',
             '아주캐피탈': '0010255',
             '롯데캐피탈': '0010259',
             'JB우리캐피탈': '0010267',
             '하나캐피탈': '0010268',
             '현대캐피탈': '0010271',
             '알씨아이파이낸셜서비스코리아': '0011575',
             '애큐온캐피탈': '0011735',
             '엔에이치농협캐피탈': '0011797',
             '제이티캐피탈': '0011923',
             'BNK캐피탈': '0012452',
             'KB국민카드': '0012627',
             '우리카드': '0013361',
             '하나카드 ': '0013640', }

SAVINGS_BANK_CODE = {'HK저축은행': '0010345',
                     'OSB저축은행': '0010346',
                     'DB저축은행': '0010349',
                     '스카이저축은행': '0010350',
                     '민국저축은행': '0010354',
                     '푸른저축은행': '0010356',
                     '삼보상호저축은행': '0010358',
                     '키움YES저축은행': '0010359',
                     '더케이저축은행': '0010363',
                     '조은저축은행': '0010366',
                     'SBI저축은행': '0010370',
                     '신안저축은행': '0010378',
                     '유진저축은행': '0010388',
                     '유안타저축은행': '0010389',
                     '고려저축은행': '0010390',
                     '국제저축은행': '0010391',
                     'DH저축은행': '0010404',
                     '흥국저축은행': '0010416',
                     '우리저축은행': '0010418',
                     '인성저축은행': '0010419',
                     '금화저축은행': '0010421',
                     '인천저축은행': '0010426',
                     '모아저축은행': '0010430',
                     '대백저축은행': '0010437',
                     '유니온저축은행': '0010438',
                     'MS저축은행': '0010439',
                     '안국저축은행': '0010448',
                     '남양저축은행': '0010449',
                     '부림저축은행': '0010453',
                     '키움저축은행': '0010456',
                     '삼정저축은행': '0010457',
                     '평택상호저축은행': '0010460',
                     '안양저축은행': '0010463',
                     '영진상호저축은행': '0010464',
                     '융창저축은행': '0010467',
                     '세람저축은행': '0010468',
                     '페퍼저축은행': '0010471',
                     '공평저축은행': '0010473',
                     '한화저축은행': '0010477',
                     '강원저축은행': '0010478',
                     '대명저축은행': '0010485',
                     '아주저축은행': '0010488',
                     '청주저축은행': '0010489',
                     '한성저축은행': '0010492',
                     '세종저축은행': '0010508',
                     '아산저축은행': '0010509',
                     '오투저축은행': '0010510',
                     '스타저축은행': '0010521',
                     '대한저축은행': '0010526',
                     '동양저축은행': '0010527',
                     '더블저축은행': '0010528',
                     '센트럴저축은행': '0010533',
                     '스마트저축은행': '0010534',
                     '한국투자저축은행': '0010537',
                     '구미저축은행': '0010550',
                     '드림저축은행': '0010551',
                     '대아저축은행': '0010553',
                     '머스트삼일저축은행': '0010556',
                     '참저축은행': '0010560',
                     '오성저축은행': '0010562',
                     '대원저축은행': '0010568',
                     'S&amp;T;저축은행': '0010569',
                     '솔브레인저축은행': '0010572',
                     '동원제일저축은행': '0010574',
                     '조흥저축은행': '0010575',
                     '진주저축은행': '0010576',
                     '예가람저축은행': '0011551',
                     'JT저축은행': '0011767',
                     '삼호저축은행': '0012120',
                     'NH저축은행': '0012711',
                     '대신저축은행': '0012840',
                     'IBK저축은행': '0012889',
                     'BNK저축은행': '0013002',
                     'KB저축은행': '0013127',
                     '하나저축은행': '0013166',
                     'JT친애저축은행': '0013308',
                     '신한저축은행': '0013313',
                     '웰컴저축은행': '0013350',
                     'OK저축은행': '0013351', }


INSURANCE_CODE = {'한화생명보험': '0010593',
                  '에이비엘생명보험': '0010594',
                  '삼성생명보험': '0010595',
                  '흥국생명보험': '0010596',
                  '교보생명보험': '0010597',
                  '신한생명보험': '0010599',
                  'KDB생명보험': '0010607',
                  '미래에셋생명보험': '0010608',
                  '하나생명보험': '0010618',
                  '동양생명보험': '0010622',
                  '메리츠화재해상보험': '0010626',
                  '한화손해보험': '0010627',
                  '롯데손해보험': '0010628',
                  '흥국화재해상보험': '0010630',
                  '삼성화재해상보험': '0010633',
                  '현대해상화재보험': '0010634',
                  'KB손해보험': '0010635',
                  'DB손해보험': '0010636',
                  '에이스아메리칸화재해상보험': '0010641',
                  '악사손해보험': '0010653',
                  '현대라이프생명': '0011320',
                  '비엔피파리바카디프손해보험': '0011353',
                  '더케이손해보험': '0011354',
                  'IBK연금보험 ': '0012455',
                  '농협생명보험': '0013173',
                  '농협손해보험': '0013174',
                  '에이아이지손해보험': '0013245',
                  '엠지손해보험': '0013376',
                  '교보라이프플래닛생명보험': '0013436', }

INVESTMENT_CODE = {'하이자산운용': '0010172',
                   '신한BNP Paribas자산운용': '0010186',
                   '한화자산운용': '0010189',
                   '유경PSG자산운용': '0010209',
                   '유리자산운용': '0010211',
                   '플러스자산운용': '0010215',
                   '엔에이치아문디자산운용': '0011317',
                   '현대인베스트먼트자산운용': '0011910',
                   '디지비자산운용': '0011988',
                   '비엔케이자산운용': '0011997', }

POPULAR_TWITTERIAN1 = {'@pierre': 'Pierre Omidyar',
                       '@karaswisher': 'Kara Swisher',
                       '@nytimes': 'The New York Times',
                       '@WhiteHouse': 'The White House',
                       '@ObamaWhiteHouse': 'White House Archived',
                       '@Cmdr_Hadfield': 'Chris Hadfield',
                       '@CommonSenseEd': 'Common Sense Ed',
                       '@HillaryClinton': 'Hillary Clinton',
                       '@Alwaleed_Talal': 'الوليد بن طلال',
                       '@InstituteGC': 'Tony Blair Institute',
                       '@BillClinton': 'Bill Clinton',
                       '@HHShkMohd': 'HH Sheikh Mohammed',
                       '@CARE': 'CARE (care.org)',
                       '@BenAffleck': 'Ben Affleck',
                       '@timoreilly': "Tim O'Reilly",
                       '@Bill_Gross': 'Bill Gross',
                       '@WorldBank': 'World Bank',
                       '@UNDP': 'UN Development',
                       '@FareedZakaria': 'Fareed Zakaria',
                       '@melindagates': 'Melinda Gates',
                       '@johndoerr': 'John Doerr',
                       '@gatesed': 'Gates Education',
                       '@HarvardChanSPH': 'HarvardPublicHealth',
                       '@savechildrenuk': 'Save the Children UK',
                       '@PaulGAllen': 'Paul Allen',
                       '@SteveCase': 'Steve Case',
                       '@JeffDSachs': 'Jeffrey D. Sachs',
                       '@DFID_UK': 'DFID',
                       '@ClintonFdn': 'Clinton Foundation',
                       '@GdnDevelopment': 'Global Development',
                       '@WHO': 'WHO',
                       '@USAID': 'USAID',
                       '@DonorsChoose': 'DonorsChoose',
                       '@CaseFoundation': 'Case Foundation',
                       '@GlobalFund': 'The Global Fund',
                       '@SusanWojcicki': 'Susan Wojcicki',
                       '@DazedKorea': 'DAZED KOREA 데이즈드 코리아',
                       '@coldplay': 'Coldplay',
                       '@ericnamofficial': '에릭남 (Eric Nam)',
                       '@EyeOfJackieChan': 'Jackie Chan',
                       '@NicoleScherzy': 'Nicole Scherzinger',
                       '@OFFICIALMLTR': 'MichaelLearnsToRock',
                       '@mcstkorea': '문화체육관광부',
                       '@sohnsukhee': '손석희',
                       '@BTS_twt': '방탄소년단',
                       '@bbcworldservice': 'BBC World Service',
                       '@euronews': 'euronews',
                       '@BBCWorld': 'BBC News (World)',
                       '@BBCNews': 'BBC News (UK)',
                       '@MetroUK': 'Metro',
                       '@EW': 'Entertainment Weekly',
                       '@yonhaptweet': '연합뉴스',
                       '@OnlyBabaSehgal': 'Baba Sehgal',
                       '@TW_nextmedia': '台灣蘋果日報 Taiwan News',
                       '@TMZLive': 'TMZ Live',
                       '@adrienbrody': 'Adrien Brody',
                       '@klustout': 'Kristie Lu Stout ✌🏽',
                       '@Independent': 'The Independent',
                       '@ralineshah': 'Raline Shah',
                       '@chaelinCL': 'CL',
                       '@AmandaSeyfried': 'Amanda Seyfried',
                       '@YoshikiOfficial': 'Yoshiki',
                       '@VibeMagazine': 'Vibe Magazine',
                       '@LiveNation': 'Live Nation',
                       '@lang_lang': 'Lang Lang',
                       '@ArianaGrande': 'Ariana Grande',
                       '@adamlambert': 'ADAM LAMBERT',
                       '@OfficialRMT': 'Roger Taylor',
                       '@OzzyOsbourne': 'Ozzy Osbourne',
                       '@UNESCO': 'UNESCO',
                       '@Davos': 'World Economic Forum',
                       '@wef': 'World Economic Forum',
                       '@withEverland': '에버랜드',
                       '@Madonna': 'Madonna',
                       '@mileniotv': 'Milenio Televisión',
                       '@aliciakeys': 'Alicia Keys',
                       '@chartnews': 'Chart News',
                       '@AdamSandler': 'Adam Sandler',
                       '@Choice37': 'Choice37',
                       '@JimmyKimmelLive': 'Jimmy Kimmel Live',
                       '@jimmykimmel': 'Jimmy Kimmel',
                       '@haeminsunim': 'Haemin Sunim',
                       '@BartBaker': 'Bart Baker',
                       '@UNICEF': 'UNICEF',
                       '@jencarlosmusic': 'Jencarlos - Oficial',
                       '@Hwangssabu': 'HWANGSSABU',
                       '@JGshock': '★Actor J-G ! ★',
                       '@hoogs': 'Brad Haugen',
                       '@lindsaylohan': 'Lindsay Lohan',
                       '@Fergie': 'Fergie',
                       '@ygent_official': 'YG FAMILY',
                       '@JimCarrey': 'Jim Carrey',
                       '@selenagomez': 'Selena Gomez',
                       '@MirandaKerr': 'Miranda Kerr',
                       '@britishmuseum': 'British Museum',
                       '@NationalGallery': 'National Gallery',
                       '@Guggenheim': 'Guggenheim Museum',
                       '@Tate': 'Tate',
                       '@NRJhitmusiconly': 'NRJ',
                       '@Google': 'Google',
                       '@YTCreators': 'YouTube Creators',
                       '@iTunes': 'iTunes',
                       '@AppleMusic': 'Apple Music',
                       '@Kia_Motors': 'Kia Motors Global',
                       '@AlfredoFlores': 'Alfredo Flores',
                       '@MAEJOR': 'Maejor',
                       '@RealJayWilliams': 'Jay Williams',
                       '@KennyHamilton': 'Kenny Hamilton',
                       '@davidblaine': 'David Blaine',
                       '@LennyKravitz': 'Lenny Kravitz',
                       '@CNN': 'CNN',
                       '@etnow': 'Entertainment Tonight',
                       '@USATODAY': 'USA TODAY',
                       '@WSJ': 'The Wall Street Journal',
                       '@washingtonpost': 'Washington Post',
                       '@AP': 'The Associated Press',
                       '@souljaboy': 'Soulja Boy Tell ‘Em',
                       '@BigSean': 'Sean Don',
                       '@NayaRivera': 'Naya Rivera',
                       '@Much': 'MUCH',
                       '@love_tangle': 'Junghwa Uhm',
                       '@JIFromAndromeda': '정인',
                       '@seungu97': '유승우',
                       '@CULTWOcrazycow': '컬투정찬우',
                       '@RepublicRecords': 'Republic Records',
                       '@NathanSykes': 'Nathan Sykes',
                       '@SivaKaneswaran': 'Siva Kaneswaran',
                       '@JayMcGuiness': 'Jay McGuiness',
                       '@TomParker': 'Thomas Parker',
                       '@Hyundai': 'Hyundai USA',
                       '@Kia': 'Kia Motors America',
                       '@yael': 'Yael Cohen Braun',
                       '@BGT': "Britain's Got Talent",
                       '@officialjaden': 'Jaden Smith',
                       '@THEVOICE_ITALY': 'The VOICE of ITALY', }

POPULAR_TWITTERIAN2 = {'@CoryBooker': 'Cory Booker',
                       '@biz': 'Biz Stone',
                       '@FastCompany': 'Fast Company',
                       '@charitywater': 'charity: water',
                       '@Water': 'Water.org',
                       '@FordFoundation': 'Ford Foundation',
                       '@UNAIDS': 'UNAIDS',
                       '@drsanjaygupta': 'Dr. Sanjay Gupta',
                       '@CTurlington': 'Christy Turlington',
                       '@girleffect': 'Girl Effect',
                       '@TeachForAmerica': 'Teach For America',
                       '@unfoundation': 'UN Foundation',
                       '@KatieS': 'Katie Jacobs Stanton',
                       '@wef': 'World Economic Forum',
                       '@sundancefest': 'SundanceFilmFestival',
                       '@ashleytisdale': 'Ashley Tisdale',
                       '@MSFTnews': 'Microsoft News',
                       '@Heifer': 'Heifer International',
                       '@ONECampaign': 'ONE',
                       '@MalariaNoMore': 'Malaria No More',
                       '@Rotary': 'Rotary International',
                       '@WFP': 'World Food Programme',
                       '@StevenLevy': 'Steven Levy',
                       '@QueenRania': 'Rania Al Abdullah',
                       '@CERN': 'CERN',
                       '@vkhosla': 'Vinod Khosla',
                       '@RyanSeacrest': 'Ryan Seacrest',
                       '@aplusk': 'ashton kutcher',
                       '@TED_TALKS': 'TED TALKS FANS',
                       '@TED_Tweets': 'TED Tweets',
                       '@JoePerry': 'Joe Perry',
                       '@ShinhwaCompany': 'SHINHWA OFFICIAL',
                       '@Nas': 'Nasir Jones',
                       '@Aerosmith': 'Aerosmith',
                       '@eltonofficial': 'Elton John',
                       '@Slash': 'Slash',
                       '@MickJagger': 'Mick Jagger',
                       '@jessicaalba': 'Jessica Alba',
                       '@IamStevenT': 'Steven Tyler',
                       '@DancingABC': 'Dancing with the Stars',
                       '@MileyCyrus': 'Miley Ray Cyrus',
                       '@SerieA_TIM': 'Serie A TIM',
                       '@edsheeran': 'Ed Sheeran',
                       '@PrincessRGM': 'Rosie',
                       '@Akon': 'AKON',
                       '@AmericanIdol': 'American Idol',
                       '@ddlovato': 'Demi Lovato',
                       '@NICKIMINAJ': 'NICKI MINAJ',
                       '@pitbull': 'Pitbull',
                       '@RealTracyMorgan': 'Tracy Morgan',
                       '@jimmyfallon': 'jimmy fallon',
                       '@VanityFair': 'VANITY FAIR',
                       '@kangta': 'KangTa',
                       '@HuffPost': 'HuffPost',
                       '@Harvard': 'Harvard University',
                       '@JaredCohen': 'Jared Cohen',
                       '@KellyRipa': 'Kelly Ripa',
                       '@michaelstrahan': 'Michael Strahan',
                       '@LiveKellyRyan': 'LIVEKellyRyan',
                       '@SnoopLion': 'Snoop Lion',
                       '@Reuters': 'Reuters Top News',
                       '@HanleyRamirez': 'Hanley Ramirez ⚾️',
                       '@Dodgers': 'Los Angeles Dodgers',
                       '@CBSNews': 'CBS News',
                       '@CBS': 'CBS',
                       '@OnAirWithRyan': 'On Air/Ryan Seacrest',
                       '@BillGates': 'Bill Gates',
                       '@RollingStone': 'Rolling Stone',
                       '@HyunJinRyu99': 'Hyun-Jin Ryu',
                       '@MTVIndia': 'MTV India',
                       '@thescript': 'the script',
                       '@ActorLeeMinHo': 'Lee Min Ho',
                       '@MTVNews': 'MTV News',
                       '@tiesto': 'Tiësto',
                       '@TMZ': 'TMZ',
                       '@steveaoki': 'All Night Aoki',
                       '@iansomerhalder': 'Ian Somerhalder',
                       '@NellyFurtado': 'Nelly Furtado',
                       '@wikitree': '위키트리 WIKITREE',
                       '@dennisrodman': 'Dennis Rodman',
                       '@alpkirsan': 'alp kırşan',
                       '@hulyavsar': 'Hulya Avsar',
                       '@yetenek_turkiye': 'Yetenek Sizsiniz',
                       '@acunilicali': 'Acun Ilıcalı',
                       '@jason_mraz': 'Jason Mraz',
                       '@Tyga': 'T-Raww',
                       '@SabrinaSato': 'Sabrina Sato Rahal',
                       '@ClaudiaLeitte': 'Claudia Leitte',
                       '@TaioCruz': 'Jacob Taio Cruz',
                       '@fleurpellerin': 'Fleur Pellerin',
                       '@LeoDiCaprio': 'Leonardo DiCaprio',
                       '@nikosaliagas': 'Nikos Aliagas',
                       '@LeChrisMarques': 'Chris Marques',
                       '@RealKiefer': 'Kiefer Sutherland',
                       '@Schwarzenegger': 'Arnold',
                       '@PaulMcCartney': 'Paul McCartney',
                       '@Beyonce': 'BEYONCÉ',
                       '@MikeTyson': 'Mike Tyson',
                       '@AllisonKaye': 'Allison K Scarinzi',
                       '@SophiaBush': 'Sophia Bush',
                       '@PencilsOfPromis': 'Pencils of Promise',
                       '@neontrees': 'NEON TREES',
                       '@LilJon': 'LILJON',
                       '@QueenWillRock': 'Queen',
                       '@TheSource': 'The Source Magazine',
                       '@THR': 'Hollywood Reporter',
                       '@ConanOBrien': "Conan O'Brien",
                       '@tomhanks': 'Tom Hanks',
                       '@bobatl': 'B.o.B',
                       '@afrojack': 'Afrojack',
                       '@JLo': 'Jennifer Lopez',
                       '@2chainz': 'Tity Boi (2 Chainz)',
                       '@jayleno': 'Jay Leno',
                       '@natashaleggero': 'Natasha Leggero',
                       '@kingsthings': 'Larry King',
                       '@ForvictoRi': 'Seung Ri',
                       '@joehahnLP': 'Joe Hahn',
                       '@Yoana81': 'Yoana Jung 정려원',
                       '@BustaRhymes': 'Busta Rhymes',
                       '@muse': 'muse',
                       '@xtina': 'Christina Aguilera',
                       '@Tukutz81': 'DJ TUKUTZ',
                       '@KimKardashian': 'Kim Kardashian West',
                       '@DavidHasselhoff': 'David Hasselhoff',
                       '@heidiklum': 'Heidi Klum',
                       '@wossy': 'Jonathan Ross',
                       '@RitaOra': 'Rita Ora',
                       '@scott_mills': 'Scott Mills',
                       '@THEREALSWIZZZ': 'SWIZZ BEATZ',
                       '@people': 'People', }

POPULAR_TWITTERIAN3 = {'@TIME': 'TIME',
                       '@GStephanopoulos': 'GeorgeStephanopoulos',
                       '@BarackObama': 'Barack Obama',
                       '@ch9': 'Microsoft Channel 9',
                       '@MSFTResearch': 'Microsoft Research',
                       '@ForbesLife': 'ForbesLife',
                       '@BBCBreaking': 'BBC Breaking News',
                       '@TheEconomist': 'The Economist',
                       '@Forbes': 'Forbes',
                       '@Tesla': 'Tesla',
                       '@halfadams': 'Patrick J Adams',
                       '@mickeyk': 'Mickey Kim (미키김 김현유)',
                       '@JohnPiper': 'John Piper',
                       '@hillsongunited': 'Hillsong United',
                       '@paulwasher': 'Paul Washer',
                       '@SMTOWNGLOBAL': 'SMTOWN GLOBAL',
                       '@psy_oppa': 'PSY',
                       '@ChungMinCho': '조정민',
                       '@WhiteHouse': 'The White House',
                       '@Notebook': 'The Notebook',
                       '@diegobluff': '정태영',
                       '@cnni': 'CNN International',
                       '@Twitter': 'Twitter',
                       '@unicefkorea': '유니세프한국위원회',
                       '@bluehousekorea': '대한민국 청와대',
                       '@MissyElliott': 'Missy Elliott',
                       '@ParisHilton': 'Paris Hilton',
                       '@MichaelPhelps': 'Michael Phelps',
                       '@official_flo': 'FLO RIDA',
                       '@Pharrell': 'Pharrell Williams',
                       '@robbiewilliams': 'Robbie Williams',
                       '@iamjamiefoxx': 'Jamie Foxx',
                       '@jonmchu': 'Jon M. Chu',
                       '@diplo': 'dip',
                       '@thewanted': 'the wanted',
                       '@QuincyDJones': 'Quincy Jones',
                       '@ciara': 'Ciara',
                       '@MCHammer': 'MC HAMMER',
                       '@Eminem': 'Marshall Mathers',
                       '@Newsweek': 'Newsweek',
                       '@MariahCarey': 'Mariah Carey',
                       '@jack': 'jack',
                       '@russellcrowe': 'Russell Crowe',
                       '@JanetJackson': 'Janet Jackson',
                       '@Timbaland': 'Timbaland',
                       '@LilTunechi': 'Lil Wayne WEEZY F',
                       '@BennyBenassi': 'Benny Benassi',
                       '@Drake': 'Drizzy',
                       '@dongryulkim': '김동률 KIM DONGRYUL',
                       '@SnoopDogg': 'Snoop Dogg',
                       '@RealHughJackman': 'Hugh Jackman',
                       '@jaysean': 'Jay Sean',
                       '@OfficialMelB': 'Melanie Brown',
                       '@thexfactorau': '#XFactorAU',
                       '@AMAs': 'American Music Awards',
                       '@iamwill': 'will.i.am',
                       '@CapitalOfficial': 'Capital',
                       '@redbullracing': 'Red Bull Racing',
                       '@PerezHilton': 'Perez Hilton',
                       '@DrBrianMay': 'Dr. Brian May',
                       '@adamlevine': 'Adam Levine',
                       '@billboard': 'billboard',
                       '@SB_Projects': 'SB Projects',
                       '@Pink': 'P!nk',
                       '@Ludacris': 'Ludacris',
                       '@carlyraejepsen': 'Carly Rae Jepsen',
                       '@Diddy': 'Diddy',
                       '@ericschmidt': 'Eric Schmidt',
                       '@taolasvegas': 'TAO Las Vegas',
                       '@Redfoo': 'Redfoo',
                       '@mariamenounos': 'MARIA MENOUNOS',
                       '@NeYoCompound': 'NE-YO',
                       '@iHeartRadio': 'iHeartRadio',
                       '@BonJovi': 'Bon Jovi',
                       '@maroon5': 'Maroon 5',
                       '@ABC': 'ABC News',
                       '@CodySimpson': 'CODY SIMPSON',
                       '@MarioLopezExtra': 'Mario Lopez',
                       '@Daelim_museum': '대림미술관ㅣ디뮤지엄',
                       '@hitRECordJoe': 'Joseph Gordon-Levitt',
                       '@LA_Reid': 'LA Reid',
                       '@MIAuniverse': 'M.I.A',
                       '@ladygaga': 'Lady Gaga',
                       '@MaxGeorge': 'Max George',
                       '@rihanna': 'Rihanna',
                       '@haroobomkum': 'Bom Park',
                       '@krungy21': 'Sandara Park',
                       '@ginachoi87': 'Gina.Choi',
                       '@jtimberlake': 'Justin Timberlake',
                       '@chelseahandler': 'Chelsea Handler',
                       '@taylorswift13': 'Taylor Swift',
                       '@mtvema': 'MTV EMA',
                       '@brianwatson80': 'Brian Watson',
                       '@nbcsnl': 'Saturday Night Live - SNL',
                       '@AdamBraun': 'Adam Braun',
                       '@justinbieber': 'Justin Bieber',
                       '@Usher': 'Usher Raymond IV',
                       '@CapitalLondon': 'Capital London',
                       '@ilsang': 'ILSANG YOON',
                       '@2AMkwon': 'JO KWON',
                       '@0101xiahtic': '김준수',
                       '@2AMjinwoon': 'JIN WOON JEONG',
                       '@allkpop': 'allkpop',
                       '@NickDeMoura': 'Nick Demoura',
                       '@TODAYshow': 'TODAY',
                       '@SimonCowell': 'Simon Cowell',
                       '@KevinHart4real': 'Kevin Hart',
                       '@mingkki21': 'Minzy',
                       '@TheEllenShow': 'Ellen DeGeneres',
                       '@1215thexiahtic': '김준수',
                       '@thatrygood': 'ryan good',
                       '@Solarplant': 'Yongmaan Park',
                       '@hongcube': 'hongseongsung',
                       '@officialcharts': 'Official Charts',
                       '@chrisbrown': 'Chris Brown',
                       '@davidguetta': 'David Guetta',
                       '@LMFAO': 'LMFAO',
                       '@MTV': 'MTV',
                       '@SongSH': 'Song SeungHeon (송승헌)',
                       '@TomCruise': 'Tom Cruise',
                       '@oisoo': '이외수',
                       '@JAYBUMAOM': 'JAY BUM PARK',
                       '@harooluvstar': 'Park Bom',
                       '@britneyspears': 'Britney Spears', }

POPULAR_TWITTERIAN4 = {'@camanpour': 'Christiane Amanpour',
                       '@udemy': 'Udemy',
                       '@edmodo': 'Edmodo',
                       '@TheMandyMoore': 'Mandy Moore',
                       '@johnlegend': 'John Legend',
                       '@SavetheChildren': 'Save the Children US',
                       '@GlobalGoalsUN': 'Global Goals',
                       '@khanacademy': 'Khan Academy',
                       '@Acumen': 'Acumen',
                       '@TechCrunch': 'TechCrunch',
                       '@Oprah': 'Oprah Winfrey',
                       '@UN': 'United Nations',
                       '@paulocoelho': 'Paulo Coelho',
                       '@Kjjzz': '김종진',
                       '@Himsenkangin': 'Kang in',
                       '@GaemGyu': 'ChoKyuHyun',
                       '@special1004': 'Lee Teuk',
                       '@ShinsFriends': '신동',
                       '@AllRiseSilver': 'Dalnim',
                       '@donghae861015': 'Super Junior 이동해',
                       '@Jun2daKAY': 'JUN. K',
                       '@nanurime': '나를 찾아서',
                       '@BaikJiYeon': '백지연',
                       '@instagram': 'Instagram',
                       '@2PMagreement211': '황찬성',
                       '@hoya1991': 'Lee howon',
                       '@leadergyu': '김성규',
                       '@kyuzizi': '김성규',
                       '@infiniteyounges': '인스피릿♡성종',
                       '@Girls_Day_Yura': '걸스데이유라',
                       '@chocolatecat9': 'kim jung eun',
                       '@kahi_korea': 'kahi jiyoung park',
                       '@siwonchoi': 'Siwon Choi',
                       '@katyperry': 'KATY PERRY',
                       '@asherroth': 'Asher Roth',
                       '@TalkinPark': 'Park Kyeong Rim',
                       '@YouTube': 'YouTube',
                       '@JYPESuzy': '숮이',
                       '@le_petit_piano': 'Jae-Hyung.JUNG',
                       '@followjyp': 'JY Park',
                       '@29rain': 'RAIN',
                       '@SANGCHUKANGCHU': 'CHU(Mighty Mouth)',
                       '@cherry4eva84': '이다해 lee da hae',
                       '@joshgroban': 'josh groban',
                       '@scooterbraun': 'Scooter Braun',
                       '@TPAIN': 'T-Pain',
                       '@Realtaeyang': 'TAEYANG',
                       '@VERBAL_AMBUSH': 'VERBAL',
                       '@1003Grace': 'YoonEunHye♥윤은혜',
                       '@jinuSEAN3000': 'Sean Ro',
                       '@blobyblo': '타블로 | Tablo of Epik High',
                       '@IBGDRGN': 'G-DRAGON',
                       '@AsiaPrince_JKS': 'Jang Keun Suk 장근석',
                       '@DrunkenTigerJK': '아빠 최고',
                       '@Quanninomarley': 'ha dong hoon',
                       '@keumkangkyung': 'Jedong Kim',
                       '@Brlove12': '남희석♥남본좌',
                       '@teoinmbc': 'TAEHO KIM',
                       '@BSKworld': 'Kimbumsoo',
                       '@usraman': '윤형빈',
                       '@babospmc': 'SIMON Dominic 쌈디',
                       '@KihaChang': '장기하 Kiha Chang',
                       '@_911007': 'Nicole',
                       '@doc0102': 'DJ DOC 김창열',
                       '@jucklee': '이적 Juck Lee',
                       '@Yoonmirae': '윤미래 Yoonmirae',
                       '@officialse7en': '세븐 SE7EN',
                       '@flyx2NAL': 'Narsha 나르샤',
                       '@gaekogeem': 'Gaeko of Dynamicduo',
                       '@moviejhp': '박중훈 Joonghoon Park',
                       '@Juna0465': '정준하',
                       '@KimSooro': '김수로',
                       '@kolleen22': 'kolleen park 박칼린',
                       '@dambi925': 'sondambi',
                       '@_sweethara': 'HARAGU',
                       '@kanggary58': '강개리',
                       '@LUCKYHONGCHUL': '노홍철',
                       '@leegiug': 'Lee, Giug',
                       '@jkh115': '스포츠게임',
                       '@m_twi': 'mountain',
                       '@NelsonMandela': 'NelsonMandela',
                       '@senatwt': '세나',
                       '@from_c': 'from',
                       '@happylotteworld': '롯데월드',
                       '@south999': '겨울산',
                       '@Bulloger': '송영길',
                       '@VWOfficial': 'Vanessa Williams',
                       '@EvaLongoria': 'Eva Longoria Baston',
                       '@ReallyMarcia': 'Marcia Cross',
                       '@FelicityHuffman': 'Felicity Huffman',
                       '@kimhs0927': '김형석 PD.K',
                       '@ChooMiAe': '추미애',
                       '@six2k': 'Sung Jun',
                       '@Wit_of_Wilde': 'Oscar Wilde',
                       '@newscientist': 'New Scientist',
                       '@sciam': 'Scientific American',
                       '@NYTScience': 'NYT Science',
                       '@NatureNews': 'Nature News & Comment',
                       '@WIREDScience': 'WIRED Science',
                       '@sciencemagazine': 'Science Magazine',
                       '@ScienceNews': 'Science News',
                       '@Discovery': 'Discovery',
                       '@ScienceChannel': 'Science Channel',
                       '@lhc21net': '세종무한책임! 이해찬 국회의원실',
                       '@AS_JungAh': 'jung-A',
                       '@p_Lizzy': 'Lizzy Park 리지',
                       '@songjieun_55': 'SONGJIEUN',
                       '@4M_jiyoonitt': '전지윤',
                       '@4M_kkwonsso': '권소현',
                       '@df60b64ee5b444a': '오현민',
                       '@ActorJungilwoo': 'Jung Il Woo 정일우',
                       '@spbabojs': '머독P',
                       '@pdgreatspirit': 'PD대정령',
                       '@BTOB_IMHYUNSIK': '임현식',
                       '@LeeCS_BTOB': '이창섭',
                       '@ljoeljoe1123': '😇',
                       '@ArtinAmerica': 'Art in America',
                       '@TheArtNewspaper': 'The Art Newspaper',
                       '@ARTnewsmag': 'ARTnews',
                       '@ArtReview_': 'ArtReview',
                       '@_WhiteCube': 'White Cube',
                       '@frieze_magazine': 'frieze',
                       '@Artforum': 'Artforum',
                       '@artnet': 'artnet',
                       '@FriezeArtFair': 'Frieze Fairs',
                       '@LACMA': 'LACMA',
                       '@hammer_museum': 'Hammer Museum', }

POPULAR_TWITTERIAN5 = {'@ArtBasel': 'Art Basel',
                       '@PaceGallery': 'Pace Gallery',
                       '@saatchi_gallery': 'Saatchi Gallery',
                       '@Gagosian': 'Gagosian',
                       '@narmnarmnarm': '낢, Narm',
                       '@MOCAlosangeles': 'MOCA',
                       '@kimpoong': '김풍',
                       '@MoMAPS1': 'MoMA PS1',
                       '@newmuseum': 'New Museum',
                       '@DesignMuseum': 'Design Museum',
                       '@GettyMuseum': 'J. Paul Getty Museum',
                       '@brooklynmuseum': 'Brooklyn Museum',
                       '@metmuseum': 'The Met',
                       '@whitneymuseum': 'Whitney Museum',
                       '@luckymessage': '김수연',
                       '@OneLouderApps': 'OneLouder Apps',
                       '@MuseumModernArt': 'MoMA, the Museum of Modern Art',
                       '@YGEXStaff': 'YGEX Staff',
                       '@torrentcupnet': '토렌트킴',
                       '@lily199iu': '이지은',
                       '@BTSARMY_INTL': 'BTS INTERNATIONAL',
                       '@USBTSARMY': 'US BTS ARMY',
                       '@BOGUMMY': '박보검',
                       '@btsdiary': 'BTSDIARY',
                       '@minaminita': 'mina sohn 손미나',
                       '@cat_bot_kr': '고양이봇',
                       '@peoplepower21': '참여연대',
                       '@BTS_ABS': 'ARMYBASESUBS',
                       '@BTSOFFICIALSHOP': '방탄소년단공식쇼핑몰',
                       '@BTS_BiTS': 'BTS_BiTS',
                       '@bangtanitl': 'ARMY Base',
                       '@BTS_Trans': 'Bangtan Translations',
                       '@reading_bot_': '독서봇🌈',
                       '@BTS_ARMY': 'BTS A.R.M.Y',
                       '@hitmanb': 'hitman',
                       '@BTS_facts': 'BTS FACTS',
                       '@BTS_National': 'BTS National',
                       '@yoeman6310': '박주민과 더민주',
                       '@chopros': '남양주갑과 더불어 조응천',
                       '@twit_reva': '레바',
                       '@dumbassgenius': 'Rick G. Rosner',
                       '@Kammuse': '싸우는 신부',
                       '@eldiarioes': 'eldiario.es',
                       '@RevistaSemana': 'Revista Semana',
                       '@elespectador': 'El Espectador',
                       '@NoticiasCaracol': 'Noticias Caracol',
                       '@CaracolRadio': 'Caracol Radio',
                       '@ELTIEMPO': 'EL TIEMPO',
                       '@publico_es': 'Público',
                       '@20m': '20minutos.es',
                       '@NoticiasRCN': 'Noticias RCN',
                       '@Moonjunwon': '주원',
                       '@bbcmundo': 'BBC Mundo',
                       '@el_pais': 'EL PAÍS',
                       '@EFEnoticias': 'EFE Noticias',
                       '@abc_es': 'ABC.es',
                       '@minariboy': '서형욱 Hyung Seo',
                       '@neonbcartoon': '네온비',
                       '@rodam_Ann': '배성재',
                       '@CNNEE': 'CNN en Español',
                       '@all4b2uty': '요섭씨',
                       '@Pontifex': 'Pope Francis',
                       '@realmithrajin': '😱',
                       '@JUNO_Japan': 'JUNO_KIM Jun Ho',
                       '@randomknow_bot': '오늘의랜덤지식봇',
                       '@younhaholic': 'YOUNHA',
                       '@CocaCola_Korea': 'Coca-Cola Korea',
                       '@WM_ent': 'WMentertainment',
                       '@Seongyeol1991': '인피니트 성열',
                       '@jung_g_o': 'G.O',
                       '@_B1A4OFFICIAL': 'B1A4',
                       '@B1A4_gongchan': '공찬',
                       '@B1A4_CNU': '신우',
                       '@BARO920905': 'BARO',
                       '@SANDEUL920320': '이정환',
                       '@bts_bighit': 'BTS_official',
                       '@_jinyoung911118': '정진영',
                       '@realjonghyun90': '김종현',
                       '@bestIdolone': '주간아이돌',
                       '@ProfessorJIKim': '김종인',
                       '@viewtsky': '하늘구경 | 옛글산책',
                       '@insu7': '의료법인 경산 양지재활요양병원',
                       '@GentileJIN': '르노삼성자동차 시지대리점 김진욱',
                       '@tweetsrose': '붉은장미',
                       '@chamnet21': '박영규',
                       '@haanbija': '푸르른날에',
                       '@SJ_NEWS_JP': 'SJ_NEWS_JP',
                       '@GirlsGeneration': "Girls' Generation",
                       '@Planet_EXO': 'PLANET #EXO',
                       '@moonriver365': '문재인',
                       '@SpaceX': 'SpaceX',
                       '@elonmusk': 'Elon Musk',
                       '@WarrenBuffett': 'Warren Buffett',
                       '@andersoncooper': 'Anderson Cooper',
                       '@BillionMagazine': 'Billionaire Magazine',
                       '@Girls_Day_Sojin': '걸스데이_소진',
                       '@Girls_Day_Hyeri': '혜리',
                       '@Girls_Day_Minah': 'MiNA',
                       '@jayjameshq': 'Jay James',
                       '@fromtheline': 'youngpyo lee',
                       '@WomenParty': 'AeHui Jang',
                       '@Malala': 'Malala',
                       '@masason': '孫正義',
                       '@reddit': 'Reddit',
                       '@theresa_may': 'Theresa May',
                       '@JustinTrudeau': 'Justin Trudeau',
                       '@jnovogratz': 'Jacqueline Novogratz',
                       '@RNTata2000': 'Ratan N. Tata',
                       '@MalalaFund': 'Malala Fund',
                       '@johngreen': 'John Green',
                       '@Padmasree': 'Padmasree',
                       '@BillNye': 'Bill Nye',
                       '@narendramodi': 'Narendra Modi',
                       '@satyanadella': 'Satya Nadella',
                       '@WIRED': 'WIRED',
                       '@jeremys': 'Jeremy Stoppelman',
                       '@bgurley': 'Bill Gurley',
                       '@Atul_Gawande': 'Atul Gawande',
                       '@SrBachchan': 'Amitabh Bachchan',
                       '@sapinker': 'Steven Pinker',
                       '@tomfriedman': 'Thomas L. Friedman',
                       '@jamieoliver': 'Jamie Oliver',
                       '@Oxfam': 'Oxfam International',
                       '@richardbranson': 'Richard Branson',
                       '@good': 'GOOD',
                       '@gatesfoundation': 'Gates Foundation',
                       '@bing': 'Bing',
                       '@HansRosling': 'Remember H. Rosling',
                       '@TEDchris': 'Chris Anderson',
                       '@NickKristof': 'Nicholas Kristof',
                       '@I_Love_SAC': '예술의전당', }

# Look like advertisement, maybe BOT makes favorites count up.
# Pontifex_es : spanish
BLOCK_TWITTERIAN = {
                       '@MelodyMonthly': '윤종신',
                       '@BoAkwon': 'BoA',
                       '@BTS_jp_official': 'BTS JAPAN OFFICIAL',
                       '@Bulletproof_SG': 'BTS SG🇸🇬',
                       '@BigHitEnt': 'BigHit Entertainment',
                       '@realmudo': '무한도전',
                       '@Pontifex_es': 'Papa Francisco',
                       }
